### ISSUE TITLE
tipi .run results every time into: No such file or directory

### ISSUE THREAD

**Issue by Bjoe** [tipi-build/community-support#1]
Hi @daminetreg and @pysco68 ,

many thanks again for the "testing"-token and also for the nice conversation/explanation from you on the Meeting C++ conference.
I've been looking for a remote build solution for a long time and I really like your idea. That's why I would like to have support in my QtCreator ;-) (btw. @daminetreg did you send me the infos about the QtCreator infos?). But step by step...

I try to be first familiar with the tipi-build environment, but unfortunately I'm stuck with the simplest example.

It looks like that compiling of my example is fine, but when I try to execute my example, I got always: "No such file or directory"

Here my output:
```
e . /usr/local/share/.tipi/w/8f1ac60-HelloTipi/example.cpp
✔ [ok] CMake build recipes inferred by convention in "../8f1ac60-HelloTipi.b/24ba3b7/recipe"
Compiling "." for linux-cxx17
⏳ ✔ [ok] configured.     
⏳ ✔ [ok] built.        
Compiled executables:
▶ .:
  ● example [remote] -> tipi -t linux-cxx17 .run ./build/linux-cxx17/bin/example
Remove old comprehensive cache pack at https://api.github.com/repos/Bjoe/cache.tipi.build/releases/assets/85565023
Remove old comprehensive cache pack at https://api.github.com/repos/Bjoe/cache.tipi.build/releases/assets/85565026
Cache entry for linux-cxx17-24ba3b7abaa427bd6f6b99b9bb544fa323c5115b-build-v1-comprehensive.pack was uploaded successfully with file /usr/local/share/.tipi/w/8f1ac60-HelloTipi.b/24ba3b7/bin/elfshaker_data/packs/linux-cxx17-24ba3b7abaa427bd6f6b99b9bb544fa323c5115b-build-v1-comprehensive.pack
Index for cache entry was uploaded successfully with file /usr/local/share/.tipi/w/8f1ac60-HelloTipi.b/24ba3b7/bin/elfshaker_data/packs/linux-cxx17-24ba3b7abaa427bd6f6b99b9bb544fa323c5115b-build-v1-comprehensive.pack.idx
Remove old comprehensive cache pack at https://api.github.com/repos/Bjoe/cache.tipi.build/releases/assets/85565044
Remove old comprehensive cache pack at https://api.github.com/repos/Bjoe/cache.tipi.build/releases/assets/85565045
Cache entry for linux-cxx17-24ba3b7abaa427bd6f6b99b9bb544fa323c5115b-platform-v1-comprehensive.pack was uploaded successfully with file /usr/local/share/.tipi/w/8f1ac60-HelloTipi.b/24ba3b7/p/elfshaker_data/packs/linux-cxx17-24ba3b7abaa427bd6f6b99b9bb544fa323c5115b-platform-v1-comprehensive.pack
Index for cache entry was uploaded successfully with file /usr/local/share/.tipi/w/8f1ac60-HelloTipi.b/24ba3b7/p/elfshaker_data/packs/linux-cxx17-24ba3b7abaa427bd6f6b99b9bb544fa323c5115b-platform-v1-comprehensive.pack.idx
➜  HelloTipi git:(master) ✗ tipi .run build/remote/linux-cxx17/bin/example -t linux-cxx17
 R hello.cpp example.cpp
?? .tipi/                                                                                                                                                                                     
?? build                                                                                                                                                                                      
⏳ vault synchronized.                                                                                                                                                                        
⏳ {    ●●●      }Initial remote repository clone from /home/joerg/Development/tipi.build/HelloTipi                                                                                           
✔ tipi.build remote env : linux, hash : 0b6d73e9dbc39280616262c860ef90833d5a17ac ready.                                                                                                       
👍 tipi from tipi-build/cli is up-to-date : local : v0.0.37, remote : v0.0.37                                                                                                                 
/usr/bin/bash: build/remote/linux-cxx17/bin/example: No such file or directory
➜  HelloTipi git:(master) ✗ tipi -t linux-cxx17 .run ./build/linux-cxx17/bin/example
 R hello.cpp example.cpp
?? .tipi/                                                                                                                                                                                     
?? build                                                                                                                                                                                      
⏳ vault synchronized.                                                                                                                                                                        
⏳ {    ●●●      }Initial remote repository clone from /home/joerg/Development/tipi.build/HelloTipi                                                                                           
✔ tipi.build remote env : linux, hash : 0b6d73e9dbc39280616262c860ef90833d5a17ac ready.                                                                                                       
👍 tipi from tipi-build/cli is up-to-date : local : v0.0.37, remote : v0.0.37                                                                                                                 
/usr/bin/bash: ./build/linux-cxx17/bin/example: No such file or directory
```
I try to follow the documentation from https://tipi.build/documentation/README#getting-started
I started with `4. create an empty folder for the example project on your disk` because the installation I did on Saturday at the Meeting C++ conference. Maybe I did something wrong?
Should I set my `cache.tipi.build` repo to public so that you have the "full picture"?
Even with your `https://github.com/tipi-build/simple-example` example I have the same problem.

**Comment by daminetreg** [comment]
Thank you @Bjoe ! 
It was a real pleasure meeting you at the MeetingCpp !

Regarding QtCreator that's awesome, I couldn't do the communication yet, I will do that before end of the week I have your email or eventually will open an issue and tag you to discuss it openly. Let see what is best.

Thanks for reporting the issue, it seems the previous update broke the .run command, which deletes the symlink to the `build/` directory.

We are working on a fix to be released soon, we will notify you when the update is out.
However in the meantime you can use the following workaround, namely accessing the fix path of the build (will never change) : 
`tipi -t linux-cxx17 .run /usr/local/share/.tipi/w/8f1ac60-HelloTipi.b/24ba3b7/linux-cxx17/bin/example`

**Comment by daminetreg** [comment]
🙏  Thank you so much for reporting it to us, that's very important we fix that fast. That helps alot and mean alot to us.

**Comment by Bjoe** [comment]
Hi @daminetreg 

> Regarding QtCreator that's awesome, I couldn't do the communication yet, I will do that before end of the week I have your email or eventually will open an issue and tag you to discuss it openly. Let see what is best.
> 
Ok no problem, it's not urgent. I need first an overview/experience how tipi.build works, so I need some time.

> Thanks for reporting the issue, it seems the previous update broke the .run command, which deletes the symlink to the `build/` directory.
> 
> We are working on a fix to be released soon, we will notify you when the update is out. However in the meantime you can use the following workaround, namely accessing the fix path of the build (will never change) : `tipi -t linux-cxx17 .run /usr/local/share/.tipi/w/8f1ac60-HelloTipi.b/24ba3b7/linux-cxx17/bin/example`

Unfortunately this doesn't work either for me. See:
```
➜  HelloTipi git:(master) ✗ tipi -t linux-cxx17 build .                       
 R hello.cpp example.cpp
?? .tipi/
⏳ vault synchronized.                 
⏳ {      ●●●    }Initial remote repository clone from /home/joerg/Development/tipi.build/HelloTipi
✔ tipi.build remote env : linux, hash : 0b6d73e9dbc39280616262c860ef90833d5a17ac ready.                                                                                                       
👍 tipi from tipi-build/cli is up-to-date : local : v0.0.37, remote : v0.0.37
Cache entry found for linux-cxx17, abi_hash : 24ba3b7abaa427bd6f6b99b9bb544fa323c5115b in https://api.github.com/repos/Bjoe/cache.tipi.build/releases/83878844
Fetching cache linux-cxx17-24ba3b7abaa427bd6f6b99b9bb544fa323c5115b-platform-v1-comprehensive.pack.
⏳ Fetching cache linux-cxx17-24ba3b7abaa427bd6f6b99b9bb544fa323c5115b-platform-v1-comprehensive.pack done.
Fetching cache linux-cxx17-24ba3b7abaa427bd6f6b99b9bb544fa323c5115b-platform-v1-comprehensive.pack.idx.
⏳ Fetching cache linux-cxx17-24ba3b7abaa427bd6f6b99b9bb544fa323c5115b-platform-v1-comprehensive.pack.idx done.
Cache entry found for linux-cxx17, abi_hash : 24ba3b7abaa427bd6f6b99b9bb544fa323c5115b in https://api.github.com/repos/Bjoe/cache.tipi.build/releases/83878844
Fetching cache linux-cxx17-24ba3b7abaa427bd6f6b99b9bb544fa323c5115b-build-v1-comprehensive.pack.
⏳ Fetching cache linux-cxx17-24ba3b7abaa427bd6f6b99b9bb544fa323c5115b-build-v1-comprehensive.pack done.
Fetching cache linux-cxx17-24ba3b7abaa427bd6f6b99b9bb544fa323c5115b-build-v1-comprehensive.pack.idx.
⏳ Fetching cache linux-cxx17-24ba3b7abaa427bd6f6b99b9bb544fa323c5115b-build-v1-comprehensive.pack.idx done.
Looking for 3 files
➜  HelloTipi git:(master) ✗ tipi -t linux-cxx17 .run /usr/local/share/.tipi/w/8f1ac60-HelloTipi.b/24ba3b7/linux-cxx17/bin/example
 R hello.cpp example.cpp
?? .tipi/
?? build
⏳ vault synchronized.                 
⏳ {      ●●●    }Initial remote repository clone from /home/joerg/Development/tipi.build/HelloTipi
✔ tipi.build remote env : linux, hash : 0b6d73e9dbc39280616262c860ef90833d5a17ac ready.                                                                                                       
👍 tipi from tipi-build/cli is up-to-date : local : v0.0.37, remote : v0.0.37
/usr/bin/bash: /usr/local/share/.tipi/w/8f1ac60-HelloTipi.b/24ba3b7/linux-cxx17/bin/example: No such file or directory
```
If you need more "infos"/logs/config files etc. let me know.

**Comment by daminetreg** [comment]
> Ok no problem, it's not urgent. I need first an overview/experience how tipi.build works, so I need some time.
Thanks for your patience, I will come back ASAP, Looking forward to get you up-to-speed with tipi 😄 

Oh my bad, I'm very sorry I mistyped the pathm this one should work : 
`tipi -t linux-cxx17 .run /usr/local/share/.tipi/w/8f1ac60-HelloTipi.b/linux-cxx17/bin/example`

This should work as workaround, the fix is ready we are releasing it soon.

**Comment by Bjoe** [comment]
> > Ok no problem, it's not urgent. I need first an overview/experience how tipi.build works, so I need some time.
> > Thanks for your patience, I will come back ASAP, Looking forward to get you up-to-speed with tipi smile
> 
> Oh my bad, I'm very sorry I mistyped the pathm this one should work : `tipi -t linux-cxx17 .run /usr/local/share/.tipi/w/8f1ac60-HelloTipi.b/linux-cxx17/bin/example`
> 
After I build my example again, it works with your hint:
`tipi -t linux-cxx17 .run /usr/local/share/.tipi/w/8f1ac60-HelloTipi.b/linux-cxx17/bin/example`

Thanks for your quick answer.
I will now try to setup a more advanced example to get more experience with tipi.build....
